name: turboself_dart
description: A Turboself API wrapper
version: 1.0.0
repository: https://github.com/Skythrew/turboself_dart

environment:
  sdk: ^3.5.4

dependencies:
  http: ^1.2.2

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
